### ISSUE TITLE
Pass `filter` to `file_uris` to skip partitions

### ISSUE THREAD

**Issue by TomAugspurger** [dask-contrib/dask-deltatable#11]
I have a delta dataset that's partitioned by a couple of columns. Currently, if a user uses `filter` to select data from a subset of those columns, `dask-deltatable` will still make a dask dataframe partition for each file in the original dataset. Here's an example (this should be runnable, as long as you have requests and `adlfs`)

```python
import os
import dask_deltatable
import requests

token = requests.get("https://planetarycomputer.microsoft.com/api/sas/v1/token/ms-buildings").json()["token"]
storage_options = {"account_name": "bingmlbuildings", "sas_token": token}

df = dask_deltatable.read_delta_table(
    "az://footprints/delta/2023-04-25/ml-buildings.parquet",
    storage_options=storage_options, delta_storage_options=storage_options,
    filter=[("RegionName", "=", "Turkey")]
)

print(df)
```

Which prints out

```
Dask DataFrame Structure:
                  geometry meanHeight RegionName quadkey
npartitions=26028
                    object    float32     object   int32
                       ...        ...        ...     ...
...                    ...        ...        ...     ...
                       ...        ...        ...     ...
                       ...        ...        ...     ...
Dask Name: from-delayed, 26029 graph layers
```

It seems that `deltable.file_uris` can take the `filter` argument and correctly filter out partitions that don't match the filter. With a small change to dask-deltatable, we can forward that from the user to `deltatable`:

```diff
diff --git a/dask_deltatable/core.py b/dask_deltatable/core.py
index 383ded4..c22ddca 100644
--- a/dask_deltatable/core.py
+++ b/dask_deltatable/core.py
@@ -6,7 +6,7 @@ from urllib.parse import urlparse
 import dask
 import dask.dataframe as dd
 import pyarrow.parquet as pq
-from boto3 import Session
+# from boto3 import Session
 from dask.base import tokenize
 from dask.dataframe.io import from_delayed
 from dask.delayed import delayed
@@ -145,7 +145,7 @@ class DeltaTableWrapper(object):
             ]
         dask.compute(parts)[0]
 
-    def get_pq_files(self) -> List[str]:
+    def get_pq_files(self, partition_filters=None) -> List[str]:
         """
         get the list of parquet files after loading the
         current datetime version
@@ -154,13 +154,14 @@ class DeltaTableWrapper(object):
 
         if self.datetime is not None:
             self.dt.load_with_datetime(self.datetime)
-        return self.dt.file_uris()
+        return self.dt.file_uris(partition_filters=partition_filters)
 
     def read_delta_table(self, **kwargs) -> dd.core.DataFrame:
         """
         Reads the list of parquet files in parallel
         """
-        pq_files = self.get_pq_files()
+        filter = kwargs.get("filter")
+        pq_files = self.get_pq_files(partition_filters=filter)
         if len(pq_files) == 0:
             raise RuntimeError("No Parquet files are available")
         parts = [
```

Now if I run that, you'll see the Dask DataFrame only has 266 partitions.

```python
Dask DataFrame Structure:
                geometry meanHeight RegionName quadkey
npartitions=266
                  object    float32     object   int32
                     ...        ...        ...     ...
...                  ...        ...        ...     ...
                     ...        ...        ...     ...
                     ...        ...        ...     ...
Dask Name: from-delayed, 267 graph layers
```

I'll make a PR with this shortly.

**Comment by TomAugspurger** [comment]
Apparently passing a filter to `file_uris` is somewhat new in `deltalake`. I didn't find a changelog, but it is present in 0.8.1.

**Comment by rajagurunath** [comment]
Wow, This looks like a Massive improvement!  Thanks a lot for this detailed analysis and suggestion! Happy to help wherever I can!

**Comment by TomAugspurger** [comment]
There's one distinction I didn't appreciate before: the current `filter` argument is a *row* filter. But `file_uris` is expecting a *partition* filter. It's OK to pass a row filter to a partition filter, but it's *not* OK to try to pass a partition filter if the dataset isn't actually partitioned on that expression.

I'm going to try briefly to see if we can automatically infer what subset of `filter` to pass to `partition_filters`. If I can't get that working, then maybe we add another keyword, `partition_filter`, to handle that.

**Comment by rajagurunath** [comment]
- Makes Complete Sense, Actually I am also inclined towards having paritition_filter and filer_uris as separate Keyword arguments to the function. let me know your thoughts here!

**Comment by MrPowers** [comment]
@TomAugspurger - here's the syntax for filtering the partitions and by the column file statistics:

```python
import pyarrow as pa
import pyarrow.dataset as ds
from deltalake import DeltaTable, write_deltalake

sample_data = pa.table({
    'part': pa.array(['a', 'a', 'b', 'b', 'c', 'c']),
    'x': pa.array([1, 1, 2, 2, 3, 3])
})

write_deltalake('sample_data', sample_data, partition_by=['part'])

dt = DeltaTable('sample_data')
dt.file_uris(partition_filters=[('part', '>', 'a')])
# ['/Users/willjones/Documents/notebooks/sample_data/part=c/0-acc806b2-a96d-47cc-ac80-7607abca0a66-0.parquet',
# '/Users/willjones/Documents/notebooks/sample_data/part=b/0-acc806b2-a96d-47cc-ac80-7607abca0a66-0.parquet']

# With Dataset.get_fragments
filter = (ds.field('part') > 'a') & (ds.field('x') < 3)
fragments = dt.to_pyarrow_dataset().get_fragments(filter=filter)
list(fragment.path for fragment in fragments)
# ['part=b/0-acc806b2-a96d-47cc-ac80-7607abca0a66-0.parquet']
```

Courtesy of @wjones127 in [this issue](https://github.com/delta-io/delta-rs/issues/1329#issuecomment-1532328595).

**Comment by fjetter** [comment]
As an end user I would hope to not have to care about the difference between `partition_filter` and `filter`.

How about a `read_delta` API that is only accepting `filter` and in the background it splits the partition vs file filters itself.

In [@MrPowers example](https://github.com/dask-contrib/dask-deltatable/issues/11#issuecomment-1532379016) this would look like

```python
ddf = read_delta(
    'sample_data',
    filters=[
        ('part', '>', 'a'),
        ('x', '<', '3'),
    ]
)
assert ddf.npartitions == 1
```

Is there any reason why this should not be the top-level API?
