### ISSUE TITLE
Code review comments & next steps for this project

### ISSUE THREAD

**Issue by MrPowers** [dask-contrib/dask-deltatable#12]
Glad to see this project is still growing and adding more features.

Some high-level thoughts on the dask_deltatable:

* [delta-rs already has `DeltaTable.vacuum()`](https://delta-io.github.io/delta-rs/python/usage.html#vacuuming-tables).  Is there any reason to have vacuum in this library as well?
* [delta-rs already has `DeltaTable.history()`](https://delta-io.github.io/delta-rs/python/usage.html#history).  Can we just use what's already built into delta-rs?
* Can we bump from `deltalake==0.6.3` to `deltalake==0.8.1`?

Some suggested next steps:

* Add a LICENSE
* [Integrate the Delta Acceptance Testing reader tests](https://github.com/delta-incubator/dat/) (I am happy to help with this)
* Possibly join the [Delta Lake Slack](https://go.delta.io/slack), specifically the #delta-rs and #dat channels.  Would love to connect you with the delta-rs developers.  They're going to be really excited to see this project making so much progress!

**Comment by jacobtomlinson** [comment]
I think all of these thoughts/questions sound great @MrPowers. This repo has now been migrated to `dask-contrib`, I've added the license and also joined the Slack. 

A few questions/next steps:
- Could you close this issue and open separate issues to discuss the remaining topics you listed individually?
- Are you happy to archive your `deltadask` repo and direct folks here?
- Are there any parts of your repo that it makes sense to migrate here?
- Would you be interested in helping out with maintenance efforts in this repo?

**Comment by MrPowers** [comment]
Thanks @jacobtomlinson.  

I opened up a bunch of new issues for the individual suggestions.  I also archived [deltadask](https://github.com/MrPowers/deltadask) and added a README note to add all new potential users here.

I'll get started on some PRs for this repo soon.  Thank you!!
