### ISSUE TITLE
Migrate to dask-contrib?

### ISSUE THREAD

**Issue by jacobtomlinson** [dask-contrib/dask-deltatable#14]
We are seeing more folks in the Dask community ask about Delta Lake support. Searching through GitHub there just seems to be this repo and [deltadask](https://github.com/MrPowers/deltadask) by @MrPowers.

Given that this repo has the most traction I wondered if you have any interest in migrating this repo to the [dask-contrib](https://github.com/dask-contrib) org on GitHub to incubate the project? 

This would allow Dask developers to help you out with maintenance efforts. It also makes it easier for us to promote the project.

What do you think?

**Comment by rajagurunath** [comment]
Thank you for this proposal. I sometimes feel guilty for not being able to give this repo the attention it deserves. The help from the Dask community is much-needed and greatly appreciated for this project.

- Initially, this repo began as a simple [PR](https://github.com/dask/dask/pull/8123) to Dask, where I received a lot of help from the dask community. Even I incorporated CICD templates from dask-contrib projects for standardization.

- I am genuinely thrilled to collaborate with the Dask community and enhance this package further.

Please let me know how I can assist in migrating this project to the dask-contrib organization. Thank you in advance.

Special thanks to @MrPowers for providing suggestions for improvement from day one, and to @TomAugspurger for all the latest PRs and enhancements.

**Comment by rajagurunath** [comment]
sure thing, Thanks  @jacobtomlinson.

Transferred the repo ownership to you! please let me if you need any further help.

**Comment by jacobtomlinson** [comment]
Awesome thanks @rajagurunath! The transfer is complete. Could you also add me to the project on PyPI (I'm `jacob.tomlinson` there)?

Just FYI I'm OOTO next week but when I'm back I'll be ready to dive into maintenance here.

**Comment by rajagurunath** [comment]
Added you to the PyPI project! please check and let me know if you face any issues..

Thanks, Have a great time ! :)

**Comment by jacobtomlinson** [comment]
Fantastic thanks @rajagurunath! I've opened #15 to add a `LICENSE` file, which just needs approval from you and @TomAugspurger. Then I think we should be done.
