### ISSUE TITLE
Possibly remove vacuum from this library

### ISSUE THREAD

**Issue by MrPowers** [dask-contrib/dask-deltatable#16]
[delta-rs already has DeltaTable.vacuum()](https://delta-io.github.io/delta-rs/python/usage.html#vacuuming-tables). We should consider removing `vacuum` from this library if it's not needed.

**Comment by fjetter** [comment]
I agree that we should not double functionality.

There also appears to be some misunderstanding. This library implements another delete call on the files. IIUC `DeltaTable.vacuum` is already _deleting_ (i.e. it removes the files from store and not just from the deltalake log) all files and we don't need a dask concurrency layer to do this. @MrPowers can you confirm this?

**Comment by fjetter** [comment]
Closed by https://github.com/dask-contrib/dask-deltatable/pull/46
