### ISSUE TITLE
Possibly remove history() from this library

### ISSUE THREAD

**Issue by MrPowers** [dask-contrib/dask-deltatable#17]
[delta-rs already has DeltaTable.history()](https://delta-io.github.io/delta-rs/python/usage.html#history). 

Perhaps we should remove `history()` from this library and just use what's already built into delta-rs.

**Comment by fjetter** [comment]
+1

see also https://github.com/dask-contrib/dask-deltatable/issues/16

**Comment by fjetter** [comment]
Closed by https://github.com/dask-contrib/dask-deltatable/pull/46
