### ISSUE TITLE
Bump deltalake version

### ISSUE THREAD

**Issue by MrPowers** [dask-contrib/dask-deltatable#18]
This library is currently using an old version of `deltalake`.

Can we bump from `deltalake==0.6.3` to `deltalake==0.9.0`?

**Comment by jrbourbeau** [comment]
Ah, it looks like there was a version pin to 0.6.3 but it was recently removed in https://github.com/dask-contrib/dask-deltatable/pull/9

**Comment by jacobtomlinson** [comment]
Marking as closed by #9
