### ISSUE TITLE
Release soon?

### ISSUE THREAD

**Issue by jacobtomlinson** [dask-contrib/dask-deltatable#41]
Lots of exciting progress has been made here lately. Do we want to think about doing a release here soon?

**Comment by jrbourbeau** [comment]
Yeah, good point. A release would be good I think.

Looking at open PRs we have https://github.com/dask-contrib/dask-deltatable/pull/39 and https://github.com/dask-contrib/dask-deltatable/pull/40 at the moment. @j-bennet you opened up several issues recently and have been active here. Is now an okay time to release? Should we wait for more PRs? My guess is releasing here is relatively cheap, so we could do often

**Comment by j-bennet** [comment]
@jrbourbeau @jacobtomlinson I agree, releasing soon would be good. I think we should clean up the API a little before doing that:

* https://github.com/dask-contrib/dask-deltatable/issues/42

**Comment by fjetter** [comment]
Everything is in and I think a release is overdue now. I'll take care of it (now)

**Comment by jacobtomlinson** [comment]
Thanks @fjetter
