### ISSUE TITLE
Finalize API for writing Delta Tables

### ISSUE THREAD

**Issue by j-bennet** [dask-contrib/dask-deltatable#42]
The initial API for writing Delta Lake is a little bit clunky for the user.

When reading, users have to do something like this:

```python
from dask_deltatalbe import read_delta_table
ddf = read_delta_table("path_to_table")
```

To write, they need this:

```python
from dask_deltatable.write import to_deltalake
out = to_deltalake("path_to_table", ddf)
out.compute()
```

TODO:

* naming is not consistent; `read_delta_table` vs `to_deltalake`. Either of the following combos would be more consistent:
  1. `read_delta_table/write_delta_table`
  2. `read_deltalake/write_deltalake`
  3. `read_delta_table/to_delta_table`
  4. `read_deltalake/to_deltalake`
* `to_deltalake` should be exposed on top level, same as `read_delta_table`
* user shouldn't need to call `compute` as an extra step, add `compute: bool` kwarg instead
* https://github.com/dask-contrib/dask-deltatable/issues/17
* https://github.com/dask-contrib/dask-deltatable/issues/16

**Comment by fjetter** [comment]
`read_foo` / `to_foo` is the standard terminology in dask. I believe this is true for all IO APIs we're offering, see https://docs.dask.org/en/stable/dataframe-api.html#create-dataframes and https://docs.dask.org/en/stable/dataframe-api.html#store-dataframes

I suggest `read_deltalake` and `to_deltalake`

> to_deltalake should be exposed on top level, same as read_delta_table

+ 1

> user shouldn't need to call compute.

We typically offer a compute kwarg to control this behavior. I'm fine adding this to `to_deltalake` as well.
