### ISSUE TITLE
Relax requirements pins?

### ISSUE THREAD

**Issue by TomAugspurger** [dask-contrib/dask-deltatable#7]
I noticed that the requirements for deltalake, fsspec, pyarrow, and s3fs are pinned exactly. This makes it challenging for users to use dask_deltatable in other environments which might require slightly different versions of those libraries.

Is it possible to relax those pins, or do they need to be pinned exactly?

**Comment by jrbourbeau** [comment]
Closed via https://github.com/dask-contrib/dask-deltatable/pull/9
