### ISSUE TITLE
`ImportError` with `deltalake=0.16.0`

### ISSUE THREAD

**Issue by jrbourbeau** [dask-contrib/dask-deltatable#74]
When using the `deltalake=0.16.0` release (released yesterday), I get the following error when attempting to `import dask_deltatable`

```python
Traceback (most recent call last):
  File "/Users/james/projects/coiled/etl-tpch/workflow.py", line 8, in <module>
    from pipeline.reduce import query_reduce
  File "/Users/james/projects/coiled/etl-tpch/pipeline/reduce.py", line 6, in <module>
    import dask_deltatable as ddt
  File "/Users/james/mambaforge/envs/etl-tpch/lib/python3.11/site-packages/dask_deltatable/__init__.py", line 9, in <module>
    from .write import to_deltalake as to_deltalake
  File "/Users/james/mambaforge/envs/etl-tpch/lib/python3.11/site-packages/dask_deltatable/write.py", line 18, in <module>
    from deltalake.writer import (
ImportError: cannot import name 'MAX_SUPPORTED_WRITER_VERSION' from 'deltalake.writer' (/Users/james/mambaforge/envs/etl-tpch/lib/python3.11/site-packages/deltalake/writer.py)
```

**Comment by ItSolGood** [comment]
FYI, I have to go back to deltalake==0.13.0 to be able to run `import dask_deltatable as ddt`. Recent versions don't seem to be compatible anymore.

**Comment by jrbourbeau** [comment]
@ItSolGood FWIW you may try using the current `main` branch of this repo if using a more recent version of `deltalake` is important to you. The changes in https://github.com/dask-contrib/dask-deltatable/pull/68 (on `main`, but not yet released) should allow you to use something more recent than 0.13.0

**Comment by ItSolGood** [comment]
Good to know, thank you.

**Comment by avriiil** [comment]
hey @jrbourbeau :) any ETA on a new release of `dask-deltatable`? It would be nice to remove the version warning on [this delta docs page](https://delta-io.github.io/delta-rs/integrations/delta-lake-dask/) since #68 and #78 seem to have resolved the version pinning issues
