### ISSUE TITLE
Example in Readme not reproducible

### ISSUE THREAD

**Issue by ItSolGood** [dask-contrib/dask-deltatable#75]
The last example in README says: 

`ddt.to_deltalake(df, "s3://bucket_name/delta_path")`

However, this does not seem compatible with the latest version of dask-deltatable. It should be instead:

`ddt.to_deltalake("s3://bucket_name/delta_path", df)` 

or to keep the initial order of arguments:

`ddt.to_deltalake(df=df, table_or_uri="s3://bucket_name/delta_path")`

**Comment by jacobtomlinson** [comment]
You're right, I ran into this the other day too. Do you have any interest in opening a PR to fix this?

**Comment by ItSolGood** [comment]
Happy too. First time that I make one though, so please bear with me.
